easy_admin:


    entities:
        # List the entity class name you want to manage
        Clients:
            class: App\Entity\Clients

        Cours:
            class: App\Entity\Cours
        Horaires:
            class: App\Entity\Horaires
        Salles:
            class: App\Entity\Salles



            user:
                display_name: true
                display_avatar: false

